send_notification:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: brrr
    title:
      selector:
        text:
    message:
      required: true
      selector:
        text:
          multiline: true
    appearance:
      collapsed: true
      fields:
        subtitle:
          selector:
            text:
        icon_url:
          selector:
            text:
              type: url
        icon_media:
          selector:
            media:
              accept:
                - image/*
        image_url:
          selector:
            text:
              type: url
        image_media:
          selector:
            media:
              accept:
                - image/*
    delivery_options:
      collapsed: true
      fields:
        thread_id:
          selector:
            text:
        open_url:
          selector:
            text:
        sound:
          selector:
            select:
              translation_key: sound
              mode: dropdown
              options:
                - default
                - system
                - brrr
                - bell_ringing
                - bubble_ding
                - bubbly_success_ding
                - cat_meow
                - calm1
                - calm2
                - cha_ching
                - dog_barking
                - door_bell
                - duck_quack
                - emergency
                - short_triple_blink
                - upbeat_bells
                - warm_soft_error
        interruption_level:
          selector:
            select:
              translation_key: interruption_level
              mode: dropdown
              options:
                - passive
                - active
                - time-sensitive
                - critical
        volume:
          selector:
            number:
              min: 0
              max: 1
              step: 0.1
              mode: slider
        filter_criteria:
          selector:
            text:
        expiration_date:
          selector:
            datetime:

cleanup_media:
  fields: {}
